name: PostgreSQL IB Collector (Branch)
run-name: ${{ github.actor }} is Collecting a Branch! ðŸš€
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  Date:
    runs-on: ubuntu-24.04
    outputs:
      Date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: DATE
        run: |
          echo "Setting Date"
          echo "DATE=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo -e "\nWrote to file:\n$GITHUB_OUTPUT\n"
          echo "Values:"
          cat $GITHUB_OUTPUT

  Skopeo:
    needs: [Date]
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Skopeo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y skopeo pigz

      - name: DSO Login
        run: |
          skopeo login registry1.dso.mil \
            -u ${{ secrets.REGISTRY_USER }} \
            -p ${{ secrets.REGISTRY_TOKEN }}

      - name: Run Skopeo Sync
        run: |
          skopeo sync \
            --src yaml --dest dir \
            ${{ vars.COLLECTOR }}.yml \
            ${{ vars.COLLECTOR }}

      - name: Grab helm
        run: |
          mkdir -p ${{ vars.COLLECTOR }}/helmchart
          cd ${{ vars.COLLECTOR }}/helmchart
          echo -e "\nSet repo and pull chart"
          helm repo add postgresql https://charts.bitnami.com/bitnami/
          helm pull postgresql/postgresql
          echo -e "\nInstall helm images plugin"
          helm plugin install https://github.com/nikhilsbhat/helm-images
          echo -e "\nImages listed in chart"
          helm images get postgresql/postgresql
          sha256sum -b * \
          | tee ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.helm.sha

      - name: Directory Contents
        run: |
          echo -e "Directory Contents\n$(ls -lAhS *)"
          echo -e "\n\nDirectory Size\n$(du -hd1)"

      - name: TARchive Skopeo Output
        run: |
          tar -cv -Ipigz --remove-files \
            -f ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz ${{ vars.COLLECTOR }} \
          | tee ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz.txt

      - name: Generate Hash
        run: |
          sha256sum -b ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz | tee \
            ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz.sha
 
      - name: List files 
        run: ls -Alh ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz*

      - name: Upload TARchive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz
          if-no-files-found: error

      - name: Upload TARchive SHA
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz.sha
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz.sha
          if-no-files-found: error

      - name: Upload TARchive ToC
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz.txt
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.tgz.txt
          if-no-files-found: error

  Code:
    needs: [Date]
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Update Submodules if needed
        shell: bash
        run: git submodule update --init --recursive --remote

      - name: Bundle Repo1 code base for ${{ vars.COLLECTOR }}
        run: |
          git bundle create --progress ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle --all
          echo -e "\nDirectory Listing\n$(ls -Alht *)"

      - name: Generate Hash
        run: |
          sha256sum -b ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle | tee \
            ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle.sha

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle
          if-no-files-found: error

      - name: Upload bundle hash
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle.sha
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle.sha
          if-no-files-found: error

  MakeISO:
    runs-on: ubuntu-24.04
    needs: [Date, Code, Skopeo]
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install mkisofs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mkisofs isomd5sum wget

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ${{ vars.COLLECTOR }}

      - name: Copy README to ${{ vars.COLLECTOR }} ISO
        run: cp -v README.md ${{ vars.COLLECTOR }}/

      - name: Pull helm chart
        run: |
          mkdir -p ${{ vars.COLLECTOR }}/helmchart
          cd ${{ vars.COLLECTOR }}/helmchart
          echo -e "\nSet repo and pull chart"
          helm repo add postgresql https://charts.bitnami.com/bitnami/
          helm pull postgresql/postgresql
          echo -e "\nInstall helm images plugin"
          helm plugin install https://github.com/nikhilsbhat/helm-images
          echo -e "\nImages listed in chart"
          helm images get postgresql/postgresql
          sha256sum -b * \
          | tee ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.helm.sha

      - name: Show Artifacts
        run: ls -Alht ${{ vars.COLLECTOR }}

      - name: Generate Artifact Hash File
        run: |
          cd ${{ vars.COLLECTOR }}
          sha256sum -b *.* | tee \
            ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.sha

      - name: Upload Artifact Hash File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.sha
          path: ${{ vars.COLLECTOR }}/${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.sha
          if-no-files-found: error

      - name: ISO Table of contents
        run: |
          tree ${{ vars.COLLECTOR }} \
            | tee ${{ vars.COLLECTOR }}/${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.txt

      - name: Upload ISO ToC artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.txt
          path: ${{ vars.COLLECTOR }}/${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.txt
          if-no-files-found: error

      - name: Make ISO
        run: |
          mkisofs -J -R -v -T -l \
            -V '${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}' \
            -A '${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}' \
            -o ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso \
            ${{ vars.COLLECTOR }}

      - name: Implant MD5 sum into iso
        run: implantisomd5 ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso

      - name: Generate ISO Hash
        run: |
          sha256sum -b ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso \
          | tee ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.sha

      - name: Show ISO & Hash
        run: ls -Alh *.iso*

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso
          if-no-files-found: error

      - name: Upload ISO Hash
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.sha
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.sha
          if-no-files-found: error

  Release:
    runs-on: ubuntu-24.04
    needs: [Date, MakeISO]
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Show Artifacts
        run: ls -Alh ${{ vars.COLLECTOR }}-*.*

  Sharepoint:
    runs-on: ubuntu-24.04
    needs: [Date, MakeISO]
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Show Artifacts
        run: ls -Alh ${{ vars.COLLECTOR }}-*.*
